use anyhow::Result;
use std::fmt::{self, Display};

pub trait ResultOptionExt<T> {
    fn require_with_context<C, F>(self, f: F) -> Result<T>
    where
        C: Display + fmt::Debug + Send + Sync + 'static,
        F: FnOnce() -> C;
}

impl<T> ResultOptionExt<T> for Result<Option<T>> {
    /// Converts a `Result<Option<T>>` into a `Result<T>`, returning an error
    /// if the option is `None` or if the result is an error. The error message
    /// is generated by the provided function, which is called in both cases to
    /// provide context for the error.
    fn require_with_context<C, F>(self, f: F) -> Result<T>
    where
        C: Display + fmt::Debug + Send + Sync + 'static,
        F: FnOnce() -> C,
    {
        match self {
            Ok(Some(v)) => Ok(v),
            Ok(None) => Err(anyhow::Error::msg(f())),
            Err(e) => Err(e.context(f())),
        }
    }
}
